<?php if (Mage::getStoreConfig('fancyform/options/enable')) : ?>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald" type="text/css" />      
    
    <div id="messages_product_view">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    </div>
    
    <div class="page-title">
        <h2><?php echo Mage::getStoreConfig('fancyform/options/blocktitle') ?>
        </h2>
    </div>
    
    <div class="additional">
        <?php echo Mage::getStoreConfig('fancyform/options/additionaltext'); ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('fancyform/blocks/top'))->toHtml() ?>
        
    </div>
    
    <div class="fcf-contact">
        <div class="fcf-envelope">
            <div class="fcf-envelope-ft"></div>
            <div class="fcf-letter">
                <form class="fcf-contact-form" id="contactForm" method="post" action="<?php echo $this->getFormAction(); ?>" >
                    <div class="left">
                        <label for="message" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?> </label>
                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" cols="0" rows="5" class="textarea required-entry input-text"></textarea>
                    </div>

                    <div class="right">
                        <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                        <input type="text" name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input input-text required-entry" >
                        <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?><span class="req">(required)</span></label>
                        <input type="text" name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input input-text required-entry validate-email">
                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <input type="text" name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value=""  class="input">
                        <div class="buttons-set">
                            <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                            <button type="submit" onclick="onepageLogin(this)"  title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button">
                                <span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('fancyform/blocks/bottom'))->toHtml() ?>
    <script type="text/javascript">
        //<![CDATA[
            var contactForm = new VarienForm('contactForm', true);
            
            function onepageLogin(button){
                if(contactForm.validator && contactForm.validator.validate()){
                    jQuery("#hideit").val(1);
                }
            }
            
        //]]>
    </script>
    

    <?php if (Mage::getStoreConfig('fancyform/visual/enablejquery')) : ?>
            <script src="<?php echo $this->getSkinUrl('magazento_fancyform/js/jquery-1.7.1.min.js') ?>" type="text/javascript"></script>
    <?php endif; ?>
    <script src="<?php echo $this->getSkinUrl('magazento_fancyform/js/fancyContactForm.js') ?>" type="text/javascript"></script>
    
    <script type="text/javascript">
        
        var $j=jQuery.noConflict();
        
        jQuery(document).ready(function(){
            var options = {
                urlSubmit : '/fancyform/index/post',
                methodSubmit : 'POST',
                afterSubmit : function(res){},
                error : function(request, status, error){} ,
                stampAppearingTime : <?php echo Mage::getStoreConfig('fancyform/visual/stampAppearingTime'); ?>,
                dataType: "html",
                textAppearingTime : <?php echo Mage::getStoreConfig('fancyform/visual/textAppearingTime') ?>,
                letterMovingTime : <?php echo Mage::getStoreConfig('fancyform/visual/letterMovingTime') ?>,
                envelopeOpeningTime : <?php echo Mage::getStoreConfig('fancyform/visual/envelopeOpeningTime') ?>,
                envelopeClosingTime : <?php echo Mage::getStoreConfig('fancyform/visual/envelopeClosingTime') ?>,
                letterFadingInTime : <?php echo Mage::getStoreConfig('fancyform/visual/letterFadingInTime') ?>,
                letterFadingOutTime : <?php echo Mage::getStoreConfig('fancyform/visual/letterFadingOutTime') ?>,
                thanksText : function(res){if (res==1){ return '<?php echo Mage::getStoreConfig('fancyform/options/thanksText');
                 echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig('fancyform/blocks/confirmation'))->toHtml();
                ?>'} else{ return 'Unable to submit your request. Please, try again later'; }}
            };
            jQuery(".fcf-contact").fancyContactForm(options);
        }
        
    );		
    </script>

<?php endif; ?>
